version: 2.1
jobs:
  build linux:
    docker:
      - image: nixpkgs/nix-flakes
    parameters:
      version:
        type: string
    steps:
      - checkout
      - setup nix
      - run: nix build .#<< parameters.version >>
      - save_cache:
          key: linux-<< parameters.version >>-{{ .Revision }}-v1
          paths:
            - result

  publish linux:
    docker:
      - image: nixpkgs/nix-flakes
    steps:
      - setup nix
      - run: cachix push nix-node `cd -P result && pwd`

commands:
  setup nix:
    steps:
      - run: echo "experimental-features = nix-command flakes ca-references" > /etc/nix/nix.conf
      - run: nix profile install nixpkgs#cachix
      - run: cachix use nix-node

workflows:
  version: 2
  build and publish binaries:
    jobs:
      - build linux:
          name: build linux (v<<matrix.version>>)
          matrix:
            parameters:
              version: &versions
                - "16"
                - "16.3.0"
                - "16.2.0"
                - "16.1.0"
                - "16.0.0"
                - "15"
                - "15.14.0"
                - "15.13.0"
                - "15.12.0"
                - "15.11.0"
                - "15.10.0"
                - "15.9.0"
                - "15.8.0"
                - "15.7.0"
                - "15.6.0"
                - "15.5.1"
                - "15.5.0"
                - "15.4.0"
                - "15.3.0"
                - "15.2.1"
                - "15.2.0"
                - "15.1.0"
                - "15.0.1"
                - "15.0.0"
                - "14.17.0"
                - "14.16.1"
                - "14.16.0"
                - "14.15.5"
                - "14.15.4"
                - "14.15.3"
                - "14.15.2"
                - "14.15.1"
                - "14.15.0"
                - "14.14.0"
                - "14.13.1"
                - "14.13.0"
                - "14.12.0"
                - "14.11.0"
                - "14.10.1"
                - "14.10.0"
                - "14.9.0"
                - "14.8.0"
                - "14.7.0"
                - "14.6.0"
                - "14.5.0"
                - "14.4.0"
                - "14.3.0"
                - "14.2.0"
                - "14.1.0"

      - publish linux:
          matrix:
            parameters:
              version: *versions
          requires:
            - build linux (v<<matrix.version>>)
